---
- hosts: all
  roles:

  - role: cask_package
    packages:
    - asepsis
    - google-chrome
    - firefox
    - caffeine
    - iterm2
    - sublime-text
  - role: dock
    apps:
    - /Applications/Sublime\ Text\ 2.app
    - /Applications/Firefox.app
    - /Applications/Google\ Chrome.app
    - /Applications/iTerm.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  - role: hub
  - role: brew_package
    package_name: vim
